variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 3.x

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: Native_Build
    jobs:
      - template: jobs/build_native.yml
        parameters:
          name: windows
          vmImage: 'windows-2019'

      - template: jobs/build_native.yml
        parameters:
          name: linux
          vmImage: 'ubuntu-18.04'

      - template: jobs/build_native.yml
        parameters:
          name: mac
          vmImage: 'macOS-10.15'
