parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: '${{ parameters.name }} test package'
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'NuGet-Packed'
          targetPath: './NuGet-Packed'

      - bash: |
            mv nuget-test.config nuget.config
            echo "renamed nuget-test.config to nuget.config"
        displayName: fix nuget.config

      - bash: |
            cd tests/Managed.Tests.Package
            dotnet restore
            dotnet build --no-restore -c PackageTest
            dotnet test --no-build -c PackageTest
        displayName: test NuGet-package
